import type { LegalProcedure } from '@/app/juridique/juridique-types';

/** Registre des formalités juridiques (historique a60365b + procédures société SARL Maroc). */
export const LEGAL_PROCEDURE_CATEGORIES = [
  'Cession & parts',
  'Modifications statutaires',
  'Capital',
  'Gérance',
  'Transformations',
  'Fin de vie société',
  'Formalités RC',
  'Assemblées',
] as const;

export const LEGAL_PROCEDURES: LegalProcedure[] = [
  {
    id: 'cession_parts',
    category: 'Cession & parts',
    name: 'Cession de parts sociales',
    description: 'Acte de cession de parts entre associés (6 exemplaires)',
    fields: [
      { key: 'cedant', label: 'Nom complet du cédant', placeholder: 'Mohammed Alami' },
      { key: 'date_naissance_cedant', label: 'Date de naissance cédant', placeholder: '17/02/1980' },
      { key: 'adresse_cedant', label: 'Adresse cédant', placeholder: 'Rue Hassan II, Casablanca' },
      { key: 'cin_cedant', label: 'CIN cédant', placeholder: 'AB123456' },
      { key: 'cessionnaire', label: 'Nom complet du cessionnaire', placeholder: 'Ahmed Benali' },
      { key: 'date_naissance_cessionnaire', label: 'Date de naissance cessionnaire', placeholder: '29/07/2000' },
      { key: 'adresse_cessionnaire', label: 'Adresse cessionnaire', placeholder: 'Settat' },
      { key: 'cin_cessionnaire', label: 'CIN cessionnaire', placeholder: 'CD789012' },
      { key: 'nombre_parts', label: 'Nombre de parts (chiffres + lettres)', placeholder: '100 (CENT)' },
      { key: 'prix', label: 'Prix de cession MAD', placeholder: '10000 (DIX MILLE)' },
      { key: 'date', label: "Date de l'acte", placeholder: 'JJ/MM/AAAA' },
    ],
    promptHint: 'Genere CESSION DE PARTS SOCIALES officielle conforme au droit marocain des SARL.',
  },
  {
    id: 'entree_associe',
    category: 'Cession & parts',
    name: 'Entrée nouvel associé',
    description: "Acte d'entrée d'un nouvel associé dans la société",
    fields: [
      { key: 'nouvel_associe', label: 'Nom du nouvel associé', placeholder: 'Fatima Zahra' },
      { key: 'cin_nouvel_associe', label: 'CIN', placeholder: 'EF456789' },
      { key: 'adresse_nouvel_associe', label: 'Adresse', placeholder: 'Rabat' },
      { key: 'apport', label: 'Apport (MAD)', placeholder: '50000' },
      { key: 'parts', label: 'Nombre de parts', placeholder: '50' },
      { key: 'date', label: 'Date', placeholder: 'JJ/MM/AAAA' },
    ],
  },
  {
    id: 'transfert_siege',
    category: 'Modifications statutaires',
    name: 'Transfert de siège social',
    description: 'PV AGE + modification article siège social',
    fields: [
      { key: 'ancien_siege', label: 'Ancien siège social', placeholder: 'Ancienne adresse complète' },
      { key: 'nouveau_siege', label: 'Nouveau siège social', placeholder: 'Nouvelle adresse complète' },
      { key: 'gerant', label: 'Nom du gérant', placeholder: 'Mohammed Alami' },
      { key: 'date', label: 'Date AGE', placeholder: 'JJ/MM/AAAA' },
    ],
    promptHint: 'Genere DECISION EXTRAORDINAIRE TRANSFERT SIEGE SOCIAL avec resolutions adoptees a l unanimite.',
  },
  {
    id: 'changement_denomination',
    category: 'Modifications statutaires',
    name: 'Changement de dénomination sociale',
    description: 'PV AGE modification de la raison sociale',
    fields: [
      { key: 'ancien_nom', label: 'Ancienne raison sociale', placeholder: 'SARL ABC' },
      { key: 'nouveau_nom', label: 'Nouvelle raison sociale', placeholder: 'SARL XYZ' },
      { key: 'raison', label: 'Motif du changement', placeholder: 'Strategie commerciale' },
      { key: 'date', label: 'Date AGE', placeholder: 'JJ/MM/AAAA' },
      { key: 'gerant', label: 'Gérant', placeholder: 'Nom du gérant' },
    ],
  },
  {
    id: 'augmentation_capital',
    category: 'Capital',
    name: 'Augmentation de capital',
    description: 'PV AGE augmentation du capital social',
    fields: [
      { key: 'capital_actuel', label: 'Capital actuel (MAD)', placeholder: '100000' },
      { key: 'capital_nouveau', label: 'Nouveau capital (MAD)', placeholder: '200000' },
      { key: 'modalites', label: 'Modalités', placeholder: 'Apport en numéraire, incorporation réserves' },
      { key: 'gerant', label: 'Nom du gérant', placeholder: 'Mohammed Alami' },
      { key: 'date', label: 'Date AGE', placeholder: 'JJ/MM/AAAA' },
    ],
    promptHint: 'Genere PV AGE AUGMENTATION DU CAPITAL avec modification article capital.',
  },
  {
    id: 'reduction_capital',
    category: 'Capital',
    name: 'Réduction de capital',
    description: 'PV AGE réduction du capital social',
    stabilizing: true,
    fields: [
      { key: 'capital_actuel', label: 'Capital actuel (MAD)', placeholder: '200000' },
      { key: 'capital_nouveau', label: 'Capital après réduction (MAD)', placeholder: '100000' },
      { key: 'motif', label: 'Motif de la réduction', placeholder: 'Pertes, restructuration' },
      { key: 'modalites', label: 'Modalités', placeholder: 'Remboursement associés, annulation parts' },
      { key: 'gerant', label: 'Gérant', placeholder: 'Nom du gérant' },
      { key: 'date', label: 'Date AGE', placeholder: 'JJ/MM/AAAA' },
    ],
    promptHint: 'Genere PV AGE REDUCTION DE CAPITAL conforme au droit marocain des societes.',
  },
  {
    id: 'changement_gerance',
    category: 'Gérance',
    name: 'Changement de gérance',
    description: 'PV nomination / révocation du gérant',
    fields: [
      { key: 'ancien_gerant', label: 'Ancien gérant', placeholder: 'Nom complet' },
      { key: 'nouveau_gerant', label: 'Nouveau gérant', placeholder: 'Nom complet' },
      { key: 'cin_nouveau_gerant', label: 'CIN nouveau gérant', placeholder: 'AB123456' },
      { key: 'adresse_nouveau_gerant', label: 'Adresse nouveau gérant', placeholder: 'Adresse complète' },
      { key: 'date_prise_fonction', label: 'Date de prise de fonction', placeholder: 'JJ/MM/AAAA' },
      { key: 'date', label: 'Date AGE', placeholder: 'JJ/MM/AAAA' },
    ],
  },
  {
    id: 'demission_gerant',
    category: 'Gérance',
    name: 'Démission du gérant',
    description: 'Lettre de démission du gérant',
    fields: [
      { key: 'gerant_demissionnaire', label: 'Gérant démissionnaire', placeholder: 'Nom complet' },
      { key: 'cin_gerant', label: 'CIN', placeholder: 'AB123456' },
      { key: 'adresse_gerant', label: 'Adresse', placeholder: 'Adresse personnelle' },
      { key: 'destinataire', label: 'Destinataire (société / associés)', placeholder: 'Les associés de SARL...' },
      { key: 'date_effet', label: "Date d'effet", placeholder: 'JJ/MM/AAAA' },
    ],
  },
  {
    id: 'transformation_societe',
    category: 'Transformations',
    name: 'Transformation de société',
    description: 'Transformation de forme juridique (ex. SARL → SA)',
    stabilizing: true,
    fields: [
      { key: 'forme_actuelle', label: 'Forme actuelle', placeholder: 'SARL' },
      { key: 'forme_cible', label: 'Forme cible', placeholder: 'SA' },
      { key: 'motif', label: 'Motif', placeholder: 'Levée de fonds, croissance' },
      { key: 'date', label: 'Date AGE', placeholder: 'JJ/MM/AAAA' },
      { key: 'gerant', label: 'Gérant / mandataire', placeholder: 'Nom' },
    ],
    promptHint: 'Genere PV AGE TRANSFORMATION avec ordre du jour et resolutions types.',
  },
  {
    id: 'dissolution',
    category: 'Fin de vie société',
    name: 'Dissolution de la société',
    description: 'PV AGE décision de dissolution',
    fields: [
      { key: 'motif', label: 'Motif de dissolution', placeholder: 'Cessation activité, accord unanime' },
      { key: 'liquidateur', label: 'Nom du liquidateur', placeholder: 'Mohammed Alami' },
      { key: 'cin_liquidateur', label: 'CIN liquidateur', placeholder: 'AB123456' },
      { key: 'adresse_liquidateur', label: 'Adresse liquidateur', placeholder: 'Casablanca' },
      { key: 'date', label: 'Date AGE', placeholder: 'JJ/MM/AAAA' },
    ],
    promptHint: 'Genere PV AGE DISSOLUTION sans confondre avec la phase de liquidation.',
  },
  {
    id: 'liquidation',
    category: 'Fin de vie société',
    name: 'Mise en liquidation',
    description: 'PV nomination liquidateur et ouverture liquidation',
    fields: [
      { key: 'liquidateur', label: 'Liquidateur', placeholder: 'Nom complet' },
      { key: 'cin_liquidateur', label: 'CIN liquidateur', placeholder: 'AB123456' },
      { key: 'adresse_liquidateur', label: 'Adresse', placeholder: 'Adresse complète' },
      { key: 'date', label: 'Date', placeholder: 'JJ/MM/AAAA' },
      { key: 'gerant', label: 'Gérant / président séance', placeholder: 'Nom' },
    ],
    promptHint: 'Genere PV AGE MISE EN LIQUIDATION avec pouvoirs au liquidateur.',
  },
  {
    id: 'cloture_liquidation',
    category: 'Fin de vie société',
    name: 'Clôture de liquidation',
    description: 'PV clôture des opérations de liquidation',
    fields: [
      { key: 'liquidateur', label: 'Liquidateur', placeholder: 'Nom' },
      { key: 'boni', label: 'Boni / reliquat (MAD)', placeholder: '0 ou montant' },
      { key: 'date', label: 'Date', placeholder: 'JJ/MM/AAAA' },
    ],
  },
  {
    id: 'mise_en_sommeil',
    category: 'Formalités RC',
    name: 'Mise en sommeil',
    description: 'Demande de mise en sommeil d’activité au registre du commerce',
    stabilizing: true,
    fields: [
      { key: 'date_debut_sommeil', label: 'Date de début souhaitée', placeholder: 'JJ/MM/AAAA' },
      { key: 'duree', label: 'Durée prévue', placeholder: '12 mois' },
      { key: 'motif', label: 'Motif', placeholder: 'Absence d’activité temporaire' },
      { key: 'gerant', label: 'Gérant signataire', placeholder: 'Nom' },
      { key: 'date', label: 'Date du courrier', placeholder: 'JJ/MM/AAAA' },
    ],
    promptHint: 'Genere courrier/demande de mise en sommeil au greffe du tribunal de commerce.',
  },
  {
    id: 'radiation',
    category: 'Formalités RC',
    name: 'Radiation au registre du commerce',
    description: 'Demande de radiation après dissolution et liquidation',
    stabilizing: true,
    fields: [
      { key: 'date_dissolution', label: 'Date dissolution', placeholder: 'JJ/MM/AAAA' },
      { key: 'date_cloture_liquidation', label: 'Date clôture liquidation', placeholder: 'JJ/MM/AAAA' },
      { key: 'liquidateur', label: 'Liquidateur', placeholder: 'Nom' },
      { key: 'gerant', label: 'Signataire', placeholder: 'Nom' },
      { key: 'date', label: 'Date demande', placeholder: 'JJ/MM/AAAA' },
    ],
    promptHint: 'Genere demande de radiation RC avec liste des pieces a deposer.',
  },
  {
    id: 'pv_ago',
    category: 'Assemblées',
    name: 'PV Assemblée générale ordinaire',
    description: 'AGO annuelle — approbation des comptes, affectation',
    fields: [
      { key: 'date', label: 'Date AGO', placeholder: 'JJ/MM/AAAA' },
      { key: 'exercice', label: 'Exercice comptable', placeholder: '2025' },
      { key: 'resultat_net', label: 'Résultat net (MAD)', placeholder: '150000' },
      { key: 'affectation', label: 'Affectation du résultat', placeholder: 'Réserve, dividendes' },
      { key: 'gerant', label: 'Gérant', placeholder: 'Nom' },
    ],
  },
  {
    id: 'pv_dividendes',
    category: 'Assemblées',
    name: 'PV distribution de dividendes',
    description: 'Décision de distribution des bénéfices',
    fields: [
      { key: 'exercice', label: 'Exercice', placeholder: '2025' },
      { key: 'benefice', label: 'Bénéfice distribuable (MAD)', placeholder: '100000' },
      { key: 'dividende_par_part', label: 'Dividende par part (MAD)', placeholder: '1000' },
      { key: 'date', label: 'Date', placeholder: 'JJ/MM/AAAA' },
    ],
  },
];

export function getLegalProcedureById(id: string): LegalProcedure | undefined {
  return LEGAL_PROCEDURES.find((p) => p.id === id);
}

export function fieldLabelsForProcedure(procedure: LegalProcedure): Record<string, string> {
  return Object.fromEntries(procedure.fields.map((f) => [f.key, f.label]));
}
